# Generated by Django 3.2 on 2021-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='genres.Genre', verbose_name='Жанр фильма'),
        ),
    ]
